// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParqueBLL;

namespace ParqueBLL.Migrations
{
    [DbContext(typeof(ParqueContext))]
    [Migration("20190519011035_Parque")]
    partial class Parque
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParqueBLL.Entrada", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrada");

                    b.Property<int>("PassaporteID");

                    b.HasKey("ID");

                    b.HasIndex("PassaporteID");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("ParqueBLL.PassaporteBasico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataInicial");

                    b.Property<string>("NomeCliente");

                    b.Property<int>("NroDias");

                    b.HasKey("ID");

                    b.ToTable("Passaporte");
                });

            modelBuilder.Entity("ParqueBLL.Entrada", b =>
                {
                    b.HasOne("ParqueBLL.PassaporteBasico", "Passaporte")
                        .WithMany()
                        .HasForeignKey("PassaporteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
